# yaml-language-server: $schema=ai.yaml.json

deployments:
  - name: text-embedding-3-large
    model:
      format: OpenAI
      name: text-embedding-3-large
    sku:
      name: "Standard"
      capacity: 50
  - name: gpt-5.6-terra
    model:
      format: OpenAI
      name: gpt-5.6-terra
    sku:
      name: "GlobalStandard"
      capacity: 200
  - name: gpt-5.6-luna
    model:
      format: OpenAI
      name: gpt-5.6-luna
    sku:
      name: "GlobalStandard"
      capacity: 200
